7 review votes
pyholly/nc-games pull request #5
Opened 2023-06-01 15:23 UTC by pyholly

2023-06-01 15:52 UTC, dappernerddesigns requested changes
This is very close! I appreciate the error message if offline, your votes persist on a refresh and optimistically render. However, that button is just not accessible even to me right now, white on grey is not working. The colour change after the click is a nice touch, but this needs to be easier to see.

You also have an error on reviews with no comments, please address that.

2023-06-01 15:52 UTC, dappernerddesigns commented on src/App.css
> +  color: red;
This colour may not be coming through, your vote icon is currently grey with white text and extremely hard to see

2023-06-01 15:52 UTC, dappernerddesigns commented on src/Components/Comments.jsx
> +  }
Your comments are stuck in a loading state with a 404 for review 14. Probably because it doesn't have comments. This shouldn't be an error.

2023-06-02 09:53 UTC, Slyose reviewed
Good so far, but you need another look at your error for an unsuccessful vote! Please fix then resubmit another PR :)

2023-06-02 11:19 UTC, Slyose approved these changes
Apart from one unused variable, great stuff. HAppy to see you merge this solo

2023-06-02 11:19 UTC, Slyose commented on src/Components/ReviewInfo.jsx
> +  const click = 0;
Doesn't look like you're using this variable here anywhere else?

2023-06-02 11:29 UTC, merged